-- Assign views to ECOMM roles
GRANT SELECT ON Week_Wise_Sales TO ECOMM_SALES_MANAGER;
GRANT SELECT ON Total_Sales_Region_Wise TO ECOMM_SALES_MANAGER;
GRANT SELECT ON Top_Selling_Products TO ECOMM_SALES_MANAGER;
GRANT SELECT ON Customer_Behavior_Insights TO ECOMM_SALES_MANAGER;

GRANT SELECT ON Current_Inventory_Status TO ECOMM_INVENTORY_MANAGER;
GRANT SELECT ON Discount_Effectiveness TO ECOMM_INVENTORY_MANAGER;
GRANT SELECT ON Supplier_Lead_Times TO ECOMM_INVENTORY_MANAGER;
GRANT SELECT ON Customer_Return_Trends TO ECOMM_INVENTORY_MANAGER;

GRANT SELECT ON Current_Inventory_Status TO ECOMM_ANALYST;
GRANT SELECT ON Week_Wise_Sales TO ECOMM_ANALYST;
GRANT SELECT ON Total_Sales_Region_Wise TO ECOMM_ANALYST;
GRANT SELECT ON Top_Selling_Products TO ECOMM_ANALYST;
GRANT SELECT ON Customer_Return_Trends TO ECOMM_ANALYST;
GRANT SELECT ON Discount_Effectiveness TO ECOMM_ANALYST;
GRANT SELECT ON Supplier_Lead_Times TO ECOMM_ANALYST;
GRANT SELECT ON Customer_Purchase_Frequency TO ECOMM_ANALYST;
GRANT SELECT ON Customer_Behavior_Insights TO ECOMM_ANALYST;

GRANT SELECT ON Customer_Purchase_Frequency TO ECOMM_SALES_MANAGER;
GRANT SELECT ON Customer_Behavior_Insights TO ECOMM_SALES_MANAGER;
GRANT SELECT ON Customer_Return_Trends TO ECOMM_SALES_MANAGER;
