SET SERVEROUTPUT ON
/
CREATE OR REPLACE PROCEDURE ROLE_CLEANUP_PROCEDURE AS
    CURSOR CUR_ROLES IS SELECT ROLE FROM DBA_ROLES WHERE ROLE LIKE 'ECOMM_%';
    CURSOR CUR_USERS IS SELECT USERNAME FROM DBA_USERS WHERE USERNAME LIKE 'ECOMM_%';
    CURSOR CUR_SESSIONS IS SELECT SID, SERIAL# FROM v$session WHERE USERNAME LIKE 'ECOMM_%';
BEGIN
    -- Kill active sessions
    FOR SESS IN CUR_SESSIONS LOOP
        EXECUTE IMMEDIATE 'ALTER SYSTEM KILL SESSION ''' || SESS.sid || ',' || SESS.serial# || ''' IMMEDIATE';
    END LOOP;

    -- Drop roles
    FOR ROL IN CUR_ROLES LOOP
        EXECUTE IMMEDIATE 'DROP ROLE ' || ROL.ROLE;
    END LOOP;

    -- Drop users
    FOR USR IN CUR_USERS LOOP
        EXECUTE IMMEDIATE 'DROP USER ' || USR.USERNAME || ' CASCADE';
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('Cleanup complete. Users and roles removed.');
END;
/
EXECUTE ROLE_CLEANUP_PROCEDURE;
/

-- Creating Roles
CREATE ROLE ECOMM_ADMIN;
CREATE ROLE ECOMM_INVENTORY_MANAGER;
CREATE ROLE ECOMM_SALES_MANAGER;
CREATE ROLE ECOMM_ANALYST;

-- Granting common permissions
GRANT CREATE SESSION, CONNECT TO ECOMM_ADMIN, ECOMM_INVENTORY_MANAGER, ECOMM_SALES_MANAGER, ECOMM_ANALYST;


-- ECOMM_ADMIN (Super Admin - Full Access)
GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE, CREATE TRIGGER TO ECOMM_ADMIN;

GRANT ALL PRIVILEGES ON customers TO ECOMM_ADMIN;
GRANT ALL PRIVILEGES ON addresses TO ECOMM_ADMIN;
GRANT ALL PRIVILEGES ON customer_orders TO ECOMM_ADMIN;
GRANT ALL PRIVILEGES ON payments TO ECOMM_ADMIN;
GRANT ALL PRIVILEGES ON order_items TO ECOMM_ADMIN;
GRANT ALL PRIVILEGES ON returns TO ECOMM_ADMIN;
GRANT ALL PRIVILEGES ON products TO ECOMM_ADMIN;
GRANT ALL PRIVILEGES ON categories TO ECOMM_ADMIN;
GRANT ALL PRIVILEGES ON discounts TO ECOMM_ADMIN;
GRANT ALL PRIVILEGES ON suppliers TO ECOMM_ADMIN;
GRANT ALL PRIVILEGES ON suppliers_products TO ECOMM_ADMIN;
GRANT ALL PRIVILEGES ON inventory TO ECOMM_ADMIN;
GRANT ALL PRIVILEGES ON warehouse_orders TO ECOMM_ADMIN;
GRANT ALL PRIVILEGES ON warehouses TO ECOMM_ADMIN;


-- ECOMM_INVENTORY_MANAGER (Manages Products & Stock)
GRANT INSERT, UPDATE, DELETE ON products TO ECOMM_INVENTORY_MANAGER;
GRANT INSERT, UPDATE, DELETE ON inventory TO ECOMM_INVENTORY_MANAGER;
GRANT SELECT ON suppliers TO ECOMM_INVENTORY_MANAGER;
GRANT SELECT ON suppliers_products TO ECOMM_INVENTORY_MANAGER;
GRANT SELECT, INSERT, UPDATE ON warehouse_orders TO ECOMM_INVENTORY_MANAGER;
GRANT SELECT ON warehouses TO ECOMM_INVENTORY_MANAGER;
