SET SERVEROUTPUT ON
/
CREATE OR REPLACE PROCEDURE ROLE_CLEANUP_PROCEDURE AS
    CURSOR CUR_ROLES IS SELECT ROLE FROM DBA_ROLES WHERE ROLE LIKE 'ECOMM_%';
    CURSOR CUR_USERS IS SELECT USERNAME FROM DBA_USERS WHERE USERNAME LIKE 'ECOMM_%';
    CURSOR CUR_SESSIONS IS SELECT SID, SERIAL# FROM v$session WHERE USERNAME LIKE 'ECOMM_%';
BEGIN
    -- Kill active sessions
    FOR SESS IN CUR_SESSIONS LOOP
        EXECUTE IMMEDIATE 'ALTER SYSTEM KILL SESSION ''' || SESS.sid || ',' || SESS.serial# || ''' IMMEDIATE';
    END LOOP;

    -- Drop roles
    FOR ROL IN CUR_ROLES LOOP
        EXECUTE IMMEDIATE 'DROP ROLE ' || ROL.ROLE;
    END LOOP;

    -- Drop users
    FOR USR IN CUR_USERS LOOP
        EXECUTE IMMEDIATE 'DROP USER ' || USR.USERNAME || ' CASCADE';
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('Cleanup complete. Users and roles removed.');
END;
/
EXECUTE ROLE_CLEANUP_PROCEDURE;
/

-- Creating Roles
CREATE ROLE ECOMM_ADMIN;
CREATE ROLE ECOMM_INVENTORY_MANAGER;
CREATE ROLE ECOMM_SALES_MANAGER;
CREATE ROLE ECOMM_ANALYST;

-- Granting common permissions
GRANT CREATE SESSION, CONNECT TO ECOMM_ADMIN, ECOMM_INVENTORY_MANAGER, ECOMM_SALES_MANAGER, ECOMM_ANALYST;


-- ECOMM_ADMIN (Super Admin - Full Access)
GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE, CREATE TRIGGER TO ECOMM_ADMIN;

GRANT ALL PRIVILEGES ON customers TO ECOMM_ADMIN;
GRANT ALL PRIVILEGES ON addresses TO ECOMM_ADMIN;
GRANT ALL PRIVILEGES ON customer_orders TO ECOMM_ADMIN;
GRANT ALL PRIVILEGES ON payments TO ECOMM_ADMIN;
GRANT ALL PRIVILEGES ON order_items TO ECOMM_ADMIN;
GRANT ALL PRIVILEGES ON returns TO ECOMM_ADMIN;
GRANT ALL PRIVILEGES ON products TO ECOMM_ADMIN;
GRANT ALL PRIVILEGES ON categories TO ECOMM_ADMIN;
GRANT ALL PRIVILEGES ON discounts TO ECOMM_ADMIN;
GRANT ALL PRIVILEGES ON suppliers TO ECOMM_ADMIN;
GRANT ALL PRIVILEGES ON suppliers_products TO ECOMM_ADMIN;
GRANT ALL PRIVILEGES ON inventory TO ECOMM_ADMIN;
GRANT ALL PRIVILEGES ON warehouse_orders TO ECOMM_ADMIN;
GRANT ALL PRIVILEGES ON warehouses TO ECOMM_ADMIN;


-- ECOMM_INVENTORY_MANAGER (Manages Products & Stock)
GRANT INSERT, UPDATE, DELETE ON products TO ECOMM_INVENTORY_MANAGER;
GRANT INSERT, UPDATE, DELETE ON inventory TO ECOMM_INVENTORY_MANAGER;
GRANT SELECT ON suppliers TO ECOMM_INVENTORY_MANAGER;
GRANT SELECT ON suppliers_products TO ECOMM_INVENTORY_MANAGER;
GRANT SELECT, INSERT, UPDATE ON warehouse_orders TO ECOMM_INVENTORY_MANAGER;
GRANT SELECT ON warehouses TO ECOMM_INVENTORY_MANAGER;


-- ECOMM_SALES_MANAGER (Handles Orders & Customers)
GRANT INSERT, UPDATE, DELETE ON customer_orders TO ECOMM_SALES_MANAGER;
GRANT INSERT, UPDATE, DELETE ON order_items TO ECOMM_SALES_MANAGER;
GRANT INSERT, UPDATE, DELETE ON returns TO ECOMM_SALES_MANAGER;
GRANT INSERT, UPDATE, DELETE ON payments TO ECOMM_SALES_MANAGER;
GRANT SELECT ON customers TO ECOMM_SALES_MANAGER;
GRANT SELECT ON addresses TO ECOMM_SALES_MANAGER;


-- ECOMM_ANALYST (Access to Reports & Insights)
GRANT SELECT ON customer_orders TO ECOMM_ANALYST;
GRANT SELECT ON order_items TO ECOMM_ANALYST;
GRANT SELECT ON returns TO ECOMM_ANALYST;
GRANT SELECT ON payments TO ECOMM_ANALYST;
GRANT SELECT ON products TO ECOMM_ANALYST;
GRANT SELECT ON inventory TO ECOMM_ANALYST;
GRANT SELECT ON suppliers TO ECOMM_ANALYST;
GRANT SELECT ON categories TO ECOMM_ANALYST;
GRANT SELECT ON discounts TO ECOMM_ANALYST;
GRANT SELECT ON suppliers_products TO ECOMM_ANALYST;
GRANT SELECT ON warehouses TO ECOMM_ANALYST;
GRANT SELECT ON warehouse_orders TO ECOMM_ANALYST;
GRANT SELECT ON customers TO ECOMM_ANALYST;

-- Assign views to ECOMM roles
GRANT SELECT ON Week_Wise_Sales TO ECOMM_SALES_MANAGER;
GRANT SELECT ON Total_Sales_Region_Wise TO ECOMM_SALES_MANAGER;
GRANT SELECT ON Top_Selling_Products TO ECOMM_SALES_MANAGER;
GRANT SELECT ON Customer_Behavior_Insights TO ECOMM_SALES_MANAGER;

GRANT SELECT ON Current_Inventory_Status TO ECOMM_INVENTORY_MANAGER;
GRANT SELECT ON Supplier_Lead_Times TO ECOMM_INVENTORY_MANAGER;
GRANT SELECT ON Customer_Return_Trends TO ECOMM_INVENTORY_MANAGER;

GRANT SELECT ON Current_Inventory_Status TO ECOMM_ANALYST;
GRANT SELECT ON Week_Wise_Sales TO ECOMM_ANALYST;
GRANT SELECT ON Total_Sales_Region_Wise TO ECOMM_ANALYST;
GRANT SELECT ON Top_Selling_Products TO ECOMM_ANALYST;
GRANT SELECT ON Customer_Return_Trends TO ECOMM_ANALYST;
GRANT SELECT ON discount_effectiveness_summary TO ECOMM_ANALYST;
GRANT SELECT ON Supplier_Lead_Times TO ECOMM_ANALYST;
GRANT SELECT ON Customer_Purchase_Frequency TO ECOMM_ANALYST;
GRANT SELECT ON Customer_Behavior_Insights TO ECOMM_ANALYST;
GRANT SELECT ON sales_payment_summary TO ECOMM_ANALYST;

GRANT SELECT ON Customer_Purchase_Frequency TO ECOMM_SALES_MANAGER;
GRANT SELECT ON sales_payment_summary TO ECOMM_SALES_MANAGER;
GRANT SELECT ON Customer_Return_Trends TO ECOMM_SALES_MANAGER;

-- Grant EXECUTE privileges on your stored procedures
GRANT EXECUTE ON Onboard_Customer TO ECOMM_ADMIN;
GRANT EXECUTE ON place_restock_order TO ECOMM_INVENTORY_MANAGER;
GRANT EXECUTE ON receive_shipment TO ECOMM_INVENTORY_MANAGER;


-- Creating Users and Assigning Roles
CREATE USER ecomm_admin_user IDENTIFIED BY InvSalAdmin123;
GRANT ECOMM_ADMIN TO ecomm_admin_user;

CREATE USER ecomm_inventory_user IDENTIFIED BY InvManager123;
GRANT ECOMM_INVENTORY_MANAGER TO ecomm_inventory_user;

CREATE USER ecomm_sales_user IDENTIFIED BY SalManager123;
GRANT ECOMM_SALES_MANAGER TO ecomm_sales_user;

CREATE USER ecomm_analyst_user IDENTIFIED BY InvSalAna123;
GRANT ECOMM_ANALYST TO ecomm_analyst_user;


COMMIT;